# Aufruf:   docker compose [-f compose.yml -f compose.distroless.yml|compose.wolfi.yml] up
#           docker compose exec auto bash   # Bookworm
#           docker compose exec auto ash    # Wolfi
#             id
#             ps -ef                        # NUR Wolfi, NICHT Bookworm
#             env
#             pwd
#             ls -l dist
#             hostname
#             cat /etc/os-release
#           docker compose down

include:
  - path: ./db/postgres/compose.yml
  #- path: ./db/mysql/compose.yml
  #- path: ./db/oracle/compose.yml
  - path: ./keycloak/compose.yml
  - path: ./fakesmtp/compose.yml

# https://docs.docker.com/compose/compose-file/05-services
services:
  auto:
    image: team2/auto:2024.04.0-bookworm
    depends_on:
      db:
        condition: service_healthy
    ports:
      - published: 3000
        target: 3000
    volumes:
      - type: bind
        source: app.yml
        target: /opt/app/dist/config/resources/app.yml
        read_only: true
      - type: bind
        source: ../../log
        target: /opt/app/log
        read_only: true
      - type: bind
        source: ../../src/config/resources/tls/key.pem
        target: /opt/app/dist/config/resources/tls/key.pem
        read_only: true
      - type: bind
        source: ../../src/config/resources/tls/key.pem
        target: /opt/app/dist/config/resources/tls/key.pem
        read_only: true
      # - type: bind
      #   source: ../../src/config/resources/db/sqlite/auto.sqlite
      #   target: /opt/app/dist/config/resources/db/sqlite/auto.sqlite
    env_file: app.env
    environment:
      # https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution
      - USER_PASSWORD_ENCODED=$$argon2i$$v=19$$m=4096,t=3,p=1$$aaxA2v/9rRSPGkwYN+NQog$$27Huii1XtD3iEd62fog+04G26LRPZMHoYCI6AGKTL8M
    hostname: auto
    container_name: auto
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
